### ISSUE TITLE
Allow configuration via pyproject.toml

### ISSUE THREAD

**Issue by BrianPugh** [fredrikaverpil/creosote#182]
### What feature request would you like to suggest?

It would be nice if we could configure creosote via a `[tool.creosote]` section in `pyproject.toml`. Similar to other tools like pytest, CLI arguments could override values provided in `pyproject.toml`.

E.g.
```
[tool.creosote]
venv=".venv"
paths="my_project/"
deps-file="pyproject.toml"
sections=tool.poetry.dependencies
exclude-deps=[
    "importlib_resources",
    "pydantic",
]
```

Implementation details:
* Care must be taken to support lists for arguments that can be supplied multiple times.

### Will the feature request break backwards compatibility?

Yes, since all projects would currently have a non-existant `[tool.creosote]` section, so then the default behavior is current behavior.

**Comment by fredrikaverpil** [comment]
Thanks for this suggestion. I'm likely not going to implement this myself, but I'm open to review/accept PRs on this. Good timing @BrianPugh, just in time for hacktoberfest 2023 😉 

I would suggest that implementation for this breaks backwards compatibility and targets a 3.0.0 release. There are some changes in regards to how arguments are passed in (see `v3-args` under [features](https://github.com/fredrikaverpil/creosote#%EF%B8%8F-features)) that should become default with 3.0.0 too. So it might be a good idea to create a `3.x` branch where the `v3-args` is the default and then build from there.

**Comment by fredrikaverpil** [comment]
Thanks for this suggestion. I'm likely not going to implement this myself, but I'm open to review/accept PRs on this. Good timing @BrianPugh, just in time for [hacktoberfest](https://hacktoberfest.com) 2023 😉 

I recommend implementation for this breaks backwards compatibility and targets a 3.0.0 release. There are some changes in regards to how arguments are passed in (see `v3-args` under [features](https://github.com/fredrikaverpil/creosote#%EF%B8%8F-features)) that should become default with 3.0.0 too. So it might be a good idea to make `v3-args` the default and then build from there as part of this work.

### Steps to get started

For anyone who is interested in picking this up: the [`cli.py`](https://github.com/fredrikaverpil/creosote/blob/main/src/creosote/cli.py) file contains all the code you need to modify. I'd be happy to schedule a call or a chat to plan the work or provide guidance if it is helpful. Steps to get started:

1. Make `v3-args` the default (see `ARGS_CAN_BE_SPECIFIED_MULTIPLE_TIMES`).
3. Store hard-coded variables which hold today's default values for each CLI argument. See each `default=...` for each argparse argument.
4. Before parsing the CLI arguments (today done in `parse_args()`), read the `pyproject.toml`'s `[tool.creosote]` section. You can use [dotty-dict](https://github.com/pawelzny/dotty_dict) here if it helps to parse it, since this is already a project dependency. If values are found, use these instead of the hard-coded default values mentioned in step 3.
5. Optionally cater for being able to auto-detect the activated virtual environment (see #168), likely in step 3.
6. Finally, use the variable values for each argument's `default` value.

Then there will also be tests that will break following these changes, of course, that has to be updated.
