### ISSUE TITLE
Support sourceless packages

### ISSUE THREAD

**Issue by sanmai-NL** [fredrikaverpil/creosote#204]
### What feature request would you like to suggest?

Sometimes, packages are just bundles of external packages. For example, a `pyproject.toml` with just dev dependencies created to manage CI tooling not even targeting Python. These don't need a source code directory. Currently, Creosote requires a source directory, has a default of `src/` and crashes if it doesn't exist.

I propose that Creosote warns if `src/` doesn't exist, but doesn't crash and provides a zero exit status, possibly behind a configuration option if the fault is desired in the common case.

### Will the feature request break backwards compatibility?

No.

**Comment by fredrikaverpil** [comment]
Hi @sanmai-NL,

I'm not sure I understand this suggestion entirely.

If you don't have a `src` folder on your end, you need to explicitly specify where Creosote can find your source code. This is also true for other input parameters that Creosote need to work properly, such as the path to e.g. the `pyproject.toml`. It doesn't make sense to run Creosote on projects where there is no source code.

Can you elaborate a bit here on your use case, because I don't quite understand it.

It sounds like you'd like to run Creosote on a project with only dev-dependencies, without source code, and want to just see redundant warnings as a result. In which way does it even make sense to run Creosote here in the first place?

>... possibly behind a configuration option if the fault is desired in the common case.

A configuration option could perhaps be introduced to do what you need, but this all sounds like an extreme edge case so I don't think it's something we should make the default. Please feel free to open a PR.

> [!NOTE]
> Creosote checks which dependencies you have defined against your source code. Then it figures out if the source code isn't using those dependencies and warns you about potentially unused dependencies.
>
> In this sense, Creosote needs the source code to do its job. If you remove the source code as a required input, you're essentially going to have all dependencies reported as potentially unused.

**Comment by sanmai-NL** [comment]
@fredrikaverpil 

> Hi @sanmai-NL,
> 
> I'm not sure I understand this suggestion entirely.
> 
> If you don't have a `src` folder on your end, you need to explicitly specify where Creosote can find your source code. This is also true for other input parameters that Creosote need to work properly, such as the path to e.g. the `pyproject.toml`. It doesn't make sense to run Creosote on projects where there is no source code.
> 
> Can you elaborate a bit here on your use case, because I don't quite understand it.
> 
> It sounds like you'd like to run Creosote on a project with only dev-dependencies, without source code, and want to just see redundant warnings as a result. In which way does it even make sense to run Creosote here in the first place?

I don't entirely control when Creosote is run, this is part of a CI pipeline that triggers when a `pyproject.toml` exists. I can't test for non-existence of a directory (since those aren't tracked by Git), not in a cross-platform way without introducing a wrapper script.

I agree it's an edge case, but I want to focus on the following point. I propose that Creosote warns if `src/` doesn't exist, but doesn't crash and provides a zero exit status, possibly behind a configuration option if the fault is desired in the common case. If an `src/` or more generally a target code base doesn't exist, running Creosote may be redundant, but it's not a fault. Creosote can cut short to: no duplicate dependencies found. Currently, an unhandled exception is raised, which is not ideal in any case. It could be caught and turned into a warning.

**Comment by fredrikaverpil** [comment]
You are welcome to open a PR where you add a non-default feature (`--use-feature <feature>`) along with tests for this behavior.
